language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install coveralls codecov codeclimate-test-reporter
# command to run tests
script: coverage run --source=birdears --module pytest --capture=no --verbose tests/
env:
  - PYTHONPATH=''
after_success:
  - coveralls
  - codecov
  - codeclimate-test-reporter
