language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install coveralls
# command to run tests
script: python -m pytest -v tests/
env:
  - PYTHONPATH=''
after-success:
  coveralls
